In [1]:
import pandas as pd

df = pd.read_csv('/Users/rebeca/Desktop/BA portfolio/airbnb listings/airbnb_berlin.csv', sep=',')

In [3]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,3176,Fabulous Flat in great Location,3718,Britta,Pankow,Prenzlauer Berg Südwest,52.53471,13.41810,Entire home/apt,105.0,63,150,2025-08-09,0.76,1,140,2,First name and Last name: Nicolas Krotz <br/> ...
1,9991,Geourgeous flat - outstanding views,33852,Philipp,Pankow,Prenzlauer Berg Südwest,52.53269,13.41805,Entire home/apt,135.0,6,7,2020-01-04,0.06,1,241,0,03/Z/RA/003410-18
2,14325,Studio Apartment in Prenzlauer Berg,55531,Chris + Oliver,Pankow,Prenzlauer Berg Nordwest,52.54813,13.40366,Entire home/apt,75.0,150,26,2023-11-30,0.14,4,168,0,NaN
3,17904,Beautiful Kreuzberg studio - 3 months minimum,68997,Matthias,Neukölln,Reuterstraße,52.49419,13.42166,Entire home/apt,32.0,93,298,2025-09-02,1.57,1,72,1,NaN
4,20858,Designer Loft in Berlin Mitte,71331,Marc,Pankow,Prenzlauer Berg Südwest,52.53711,13.40888,Entire home/apt,202.0,3,140,2025-07-16,0.89,1,253,4,03/Z/RA/009767-24

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14274 entries, 0 to 14273
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              14274 non-null  int64
 1   name                            14274 non-null  object
 2   host_id                         14274 non-null  int64
 3   host_name                       14260 non-null  object
 4   neighbourhood_group             14274 non-null  object
 5   neighbourhood                   14274 non-null  object
 6   latitude                        14274 non-null  float64
 7   longitude                       14274 non-null  float64
 8   room_type                       14274 non-null  object
 9   price                           9264 non-null   float64
 10  minimum_nights                  14274 non-null  int64
 11  number_of_reviews               14274 non-null  int64
 12  last_review                     10960 non-null  object
 13  reviews_per_month               10960 non-null  float64
 14  calculated_host_listings_count  14274 non-null  int64
 15  availability_365                14274 non-null  int64
 16  number_of_reviews_ltm           14274 non-null  int64
 17  license                         9297 non-null   object
dtypes: float64(4), int64(7), object(7)
memory usage: 2.0+ MB

In [5]:
df.describe()

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm
count,1.427400e+04,1.427400e+04,14274.000000,14274.000000,9264.000000,14274.000000,14274.000000,10960.000000,14274.000000,14274.000000,14274.000000
mean,5.216123e+17,1.916958e+08,52.508918,13.402307,201.240393,39.965532,44.519476,1.298455,14.070898,146.829550,9.464061
std,5.756023e+17,2.097931e+08,0.033824,0.068137,1656.989769,53.502479,100.538730,2.083910,48.440490,140.467488,21.018333
min,3.176000e+03,1.581000e+03,52.341716,13.116893,5.000000,1.000000,0.000000,0.010000,1.000000,0.000000,0.000000
25%,2.152686e+07,1.767847e+07,52.490116,13.362065,70.000000,2.000000,1.000000,0.130000,1.000000,0.000000,0.000000
50%,5.203228e+07,8.970318e+07,52.509250,13.409885,104.000000,5.000000,8.000000,0.560000,1.000000,112.000000,1.000000
75%,1.096245e+18,3.622977e+08,52.531755,13.438165,160.000000,92.000000,40.000000,1.830000,5.000000,288.000000,10.000000
max,1.516055e+18,7.192701e+08,52.656110,13.721390,50000.000000,1125.000000,2895.000000,48.870000,311.000000,365.000000,684.000000

In [6]:
df.isnull().sum()

id                                   0
name                                 0
host_id                              0
host_name                           14
neighbourhood_group                  0
neighbourhood                        0
latitude                             0
longitude                            0
room_type                            0
price                             5010
minimum_nights                       0
number_of_reviews                    0
last_review                       3314
reviews_per_month                 3314
calculated_host_listings_count       0
availability_365                     0
number_of_reviews_ltm                0
license                           4977
dtype: int64

In [10]:
#checking for duplicates

df.isna().sum()
df.duplicated().sum()
df['id'].duplicated().sum()

np.int64(0)

In [11]:
df['last_review'] = pd.to_datetime(df['last_review'])

In [ ]:
df['reviews_per_month'] = df['reviews_per_month'].fillna(0)
df['host_name'] = df['host_name'].fillna('Unknown')
df['license'] = df['license'].fillna('No license info')

In [12]:
# Converting price to a number; anything unparseable becomes NaN (missing)
df['price'] = pd.to_numeric(df['price'], errors='coerce')

# Converting last_review text into a real date; blanks/bad values become NaT (missing date)
df['last_review'] = pd.to_datetime(df['last_review'], errors='coerce')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14274 entries, 0 to 14273
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              14274 non-null  int64
 1   name                            14274 non-null  object
 2   host_id                         14274 non-null  int64
 3   host_name                       14260 non-null  object
 4   neighbourhood_group             14274 non-null  object
 5   neighbourhood                   14274 non-null  object
 6   latitude                        14274 non-null  float64
 7   longitude                       14274 non-null  float64
 8   room_type                       14274 non-null  object
 9   price                           9264 non-null   float64
 10  minimum_nights                  14274 non-null  int64
 11  number_of_reviews               14274 non-null  int64
 12  last_review                     10960 non-null  datetime64[ns]
 13  reviews_per_month               10960 non-null  float64
 14  calculated_host_listings_count  14274 non-null  int64
 15  availability_365                14274 non-null  int64
 16  number_of_reviews_ltm           14274 non-null  int64
 17  license                         9297 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(7), object(6)
memory usage: 2.0+ MB

In [14]:
#cleaning the text columns

text_cols = ['name', 'host_name', 'neighbourhood_group', 'neighbourhood', 'room_type']

for col in text_cols:
    df[col] = df[col].astype(str).str.strip()

In [16]:
# 1. The summary — watch the gap between 75% and max
print(df['price'].describe())

# 2. The top values — are the extremes real or junk?
print(df['price'].sort_values(ascending=False).head(15).tolist())

# 3. The percentiles — where does the data stop being normal?
print(df['price'].quantile([0.95, 0.99, 0.995, 0.999]))

count     9264.000000
mean       201.240393
std       1656.989769
min          5.000000
25%         70.000000
50%        104.000000
75%        160.000000
max      50000.000000
Name: price, dtype: float64
[50000.0, 50000.0, 50000.0, 50000.0, 50000.0, 50000.0, 40000.0, 40000.0, 40000.0, 40000.0, 40000.0, 40000.0, 10007.0, 10000.0, 9999.0]
0.950      300.00
0.990      617.37
0.995      999.00
0.999    40000.00
Name: price, dtype: float64

In [18]:
df['price'].describe()
df[df['price'] > 1000]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
592,2860420,250 qm penthouse with roof terrace for photoshoot,14623546,Jean Luc,Friedrichshain-Kreuzberg,Tempelhofer Vorstadt,52.491850,13.419610,Entire home/apt,2500.0,1,18,2025-06-19,0.13,1,89,1,02/Z/RA/016750-23
1413,7807397,New York style cosy loft in Berlin,16101198,Ivan,Tempelhof - Schöneberg,Schöneberg-Süd,52.487000,13.365650,Entire home/apt,3429.0,92,5,2015-09-29,0.04,1,358,0,NaN
2290,13060403,Oasis in the urban jungle - 150 qm green/citynear,72335504,Sven,Lichtenberg,Alt-Hohenschönhausen Nord,52.556210,13.516810,Entire home/apt,1153.0,1,49,2020-07-26,0.43,1,364,0,11/Z/RA/001396-18
2801,16799799,"1 [RA] BIG house, max 36p, 14 bedr 8 bath, @su...",909226,Werner,Tempelhof - Schöneberg,Tempelhof,52.468660,13.392040,Entire home/apt,1285.0,2,41,2025-09-12,0.41,14,190,5,First name and Last name: Werner Bern <br/> Co...
3019,18402844,Peter,127498960,Vincent,Tempelhof - Schöneberg,Tempelhof,52.461070,13.383600,Entire home/apt,1200.0,1,0,NaT,NaN,1,365,0,First name and Last name: 0etamß 0ßas <br/> Co...
3285,20109066,2 bedroom lovely home in Berlin,141539959,Novasol,Pankow,Prenzlauer Berg Ost,52.539200,13.456520,Entire home/apt,9999.0,1,2,2025-03-14,0.06,2,33,1,03/Z/ZA/001564-16
3286,20109071,4 bedroom gorgeous home in Berlin,141539959,Novasol,Treptow - Köpenick,Müggelheim,52.422995,13.692659,Entire home/apt,9999.0,1,3,2023-09-11,0.07,2,332,0,09/Z/AZ/002411-20
4509,29022451,Gorki Penthouse 2,42671030,Gorki Apartments,Mitte,Brunnenstr. Süd,52.531240,13.400850,Entire home/apt,1371.0,1,2,2022-06-23,0.04,6,324,0,Legal entity name and Legal form: HRS Boarding...
4510,29022524,Gorki Penthouse 1,42671030,Gorki Apartments,Mitte,Brunnenstr. Süd,52.531500,13.402270,Entire home/apt,1697.0,1,15,2024-08-15,0.21,6,295,0,Legal entity name and Legal form: HRS Boarding...
5416,36871553,Generator Mitte - Superior Suite,270945970,Generator,Mitte,Alexanderplatz,52.525131,13.391480,Private room,1299.0,1,16,2023-06-12,0.22,32,0,0,Legal entity name and Legal form: Generator Be...
5595,38585015,Gorgeous apartment in Berlin-Bohnsdorf,141545714,Novasol,Treptow - Köpenick,Bohnsdorf,52.399715,13.577754,Entire home/apt,9999.0,1,4,2025-06-01,0.20,1,287,2,09/Z/NA/001984-19
6035,41787739,Bed in 2 Bunk Female Dorm,240204649,St Christophers Inn Berlin,Mitte,Alexanderplatz,52.526690,13.410620,Shared room,2310.0,1,4,2021-10-16,0.06,9,0,0,Legal entity name and Legal form: St. Christop...
6776,48733327,Brutalistischer Space zum Wohlfühlen,11896083,Christina,Mitte,Brunnenstr. Nord,52.547940,13.381710,Entire home/apt,1858.0,1,0,NaT,NaN,2,82,0,Legal entity name and Legal form: YOGA at Lobe...
6861,49850122,160qm2 Luxus Hausboot Mabelle Joyeuse+Sauna+Kamin,972575,Martin,Treptow - Köpenick,Schmöckwitz/Karolinenhof/Rauchfangswerder,52.379563,13.648474,Entire home/apt,1257.0,1,14,2025-07-24,0.28,3,355,4,Legal entity name and Legal form: Mother Earth...
9756,967963843443094544,Apartment Kastanienallee,521069057,Michael,Pankow,Schönholz/Wilhelmsruh/Rosenthal,52.590795,13.378143,Entire home/apt,10000.0,1,12,2025-09-05,0.53,1,356,3,03/Z/AZ/008433-23
10257,1036803354601817922,222m² Huge Penthouse with 2 bedrooms,543251525,Carlotta Apartments,Charlottenburg-Wilm.,Neue Kantstraße,52.507280,13.298826,Entire home/apt,1041.0,3,0,NaT,NaN,9,155,0,Legal entity name and Legal form: Godebo GmbH ...
10565,1082176822598766475,3 Contemporary Units Near Cathedral & TV Tower,484535538,RoomPicks,Mitte,Alexanderplatz,52.524530,13.418700,Hotel room,50000.0,1,1,2024-05-05,0.06,12,326,0,Legal entity name and Legal form: Hampton by H...
10566,1082200353872390326,"Family Fun: Central Located, Free Bfast, City ...",484535538,RoomPicks,Mitte,Alexanderplatz,52.524530,13.418700,Hotel room,50000.0,1,9,2025-09-14,0.47,12,326,1,Legal entity name and Legal form: Hampton by H...
10620,1087685373633667789,"3 Units in Business Friendly Stay, Near TV Tower",484535538,RoomPicks,Mitte,Alexanderplatz,52.524530,13.418700,Hotel room,50000.0,1,0,NaT,NaN,12,275,0,Legal entity name and Legal form: Hampton by H...
10621,1087686213626546117,Hot Breakfast l Centrally Located l 3 Units,484535538,RoomPicks,Mitte,Alexanderplatz,52.524530,13.418700,Hotel room,40000.0,1,0,NaT,NaN,12,256,0,Legal entity name and Legal form: Hampton by H...
10622,1087688115609349715,Hotel w/ Complimentary Breakfast Near TV Tower!,484535538,RoomPicks,Mitte,Alexanderplatz,52.524530,13.418700,Hotel room,50000.0,1,0,NaT,NaN,12,274,0,Legal entity name and Legal form: Hampton by H...
10623,1087688652490922334,2 Stylish Units Near Alexanderplatz | Breakfast,484535538,RoomPicks,Mitte,Alexanderplatz,52.524530,13.418700,Hotel room,40000.0,1,0,NaT,NaN,12,275,0,Legal entity name and Legal form: Hampton by H...
10624,1087689407848073045,Centrally Located Hotel | Breakfast | 2 Units,484535538,RoomPicks,Mitte,Alexanderplatz,52.524530,13.418700,Hotel room,40000.0,1,0,NaT,NaN,12,260,0,Legal entity name and Legal form: Hampton by H...
10625,1087690197551314799,2 Modern Rooms Near Berlin Cathedral and TV Tower,484535538,RoomPicks,Mitte,Alexanderplatz,52.524530,13.418700,Hotel room,40000.0,1,0,NaT,NaN,12,326,0,Legal entity name and Legal form: Hampton by H...
10626,1087691143770888713,"Comfy Room w/ Hot Breakfast, Near Alexanderplatz!",484535538,RoomPicks,Mitte,Alexanderplatz,52.524530,13.418700,Hotel room,50000.0,1,2,2024-03-31,0.10,12,275,0,Legal entity name and Legal form: Hampton by H...
10627,1087692732577620133,"Close to TV Tower, City view, Free Breakfast!",484535538,RoomPicks,Mitte,Alexanderplatz,52.524530,13.418700,Hotel room,40000.0,1,0,NaT,NaN,12,261,0,Legal entity name and Legal form: Hampton by H...
10628,1087693783348836737,"Berlin Fun: City Center, Playground, Bike Rentals",484535538,RoomPicks,Mitte,Alexanderplatz,52.524530,13.418700,Hotel room,50000.0,1,3,2025-08-23,0.50,12,275,3,Legal entity name and Legal form: Hampton by H...
10629,1087703187510461224,"Explore Berlin, 2 Units Near Museum Island",484535538,RoomPicks,Mitte,Alexanderplatz,52.524530,13.418700,Hotel room,40000.0,1,0,NaT,NaN,12,274,0,Legal entity name and Legal form: Hampton by H...
11220,1153347381591823573,"Wave-Lounge, exklusives Hausboot in Berlin",91005430,Janine,Treptow - Köpenick,Schmöckwitz/Karolinenhof/Rauchfangswerder,52.380049,13.647661,Entire home/apt,1260.0,1,10,2025-07-20,0.71,1,201,7,Legal entity name and Legal form: Einzeluntern...
11481,1187001536665833992,Exkl. Wohnung in Friedrichshain,100721489,Anita,Friedrichshain-Kreuzberg,Frankfurter Allee Süd FK,52.514363,13.458647,Entire home/apt,1500.0,1,0,NaT,NaN,1,140,0,First name and Last name: Mandy Painczyk <br/...
11593,1199052323714124847,"Event Space ""Headspace Harbour""",119922098,Richard,Treptow - Köpenick,Schmöckwitz/Karolinenhof/Rauchfangswerder,52.377190,13.644520,Entire home/apt,3800.0,1,0,NaT,NaN,2,364,0,Legal entity name and Legal form: DreiH Invest...
11917,1234473450946805436,Ferienhaus in Müggelheim mit eigener Terrasse,577475069,Pavel,Treptow - Köpenick,Müggelheim,52.408218,13.663044,Entire home/apt,8004.0,1,0,NaT,NaN,4,219,0,09/Z/AZ/001545-18
11918,1234474294833419521,Tiny Loft Berlin,577475069,Pavel,Charlottenburg-Wilm.,Volkspark Wilmersdorf,52.494040,13.328170,Entire home/apt,10007.0,1,4,2025-08-11,0.52,4,85,4,04/Z/RA/008513-19
11919,1234480152776356938,Ferienwohnung Schütze in Berlin Pankow,577475069,Pavel,Pankow,Blankenfelde/Niederschönhausen,52.587479,13.423946,Entire home/apt,9999.0,1,2,2025-07-13,0.17,4,315,2,03/Z/AZ/004069-18
11920,1234483190089885723,Appartement in Rudow mit Garten,577475069,Pavel,Neukölln,Rudow,52.416860,13.485230,Entire home/apt,9999.0,1,3,2025-03-13,0.32,4,205,3,08/Z/AF/002622-14
12101,1264383954551134984,Event Space in Friedrichshain,29669233,Fabrizio,Friedrichshain-Kreuzberg,Frankfurter Allee Süd FK,52.510167,13.455859,Entire home/apt,1440.0,1,0,NaT,NaN,2,365,0,Legal entity name and Legal form: Partenope 08...
13112,1387420362833830935,Ferienwohnung Berlin,685495832,Pavel,Tempelhof - Schöneberg,Marienfelde,52.413527,13.347841,Entire home/apt,8000.0,1,0,NaT,NaN,1,10,0,07/Z/RA/016633-23
13212,1399874907206113574,Cozy Panthouse near Schloss,688314014,Bilyal,Steglitz - Zehlendorf,Albrechtstr.,52.451939,13.328930,Entire home/apt,1200.0,100,0,NaT,NaN,1,365,0,NaN
13220,1400614727095102539,Friedrichshain Penthouse by Suite.030,102979040,Team Suite030,Friedrichshain-Kreuzberg,Frankfurter Allee Nord,52.515690,13.462390,Entire home/apt,1290.0,60,0,NaT,NaN,22,267,0,02/Z/RA/021021-25
13247,1403376087059050689,Lakeside Retreat near Berlin,468304459,Christian,Treptow - Köpenick,Rahnsdorf/Hessenwinkel,52.431820,13.687220,Entire home/apt,2407.0,1,0,NaT,NaN,5,364,0,Legal entity name and Legal form: Deep Ink Ven...
13909,1471932408346683188,Exklusives Hausboot - 90qm+,240453521,Johannes,Treptow - Köpenick,Schmöckwitz/Karolinenhof/Rauchfangswerder,52.378587,13.646416,Entire home/apt,2192.0,1,0,NaT,NaN,1,365,0,First name and Last name: Johannes Kirsch <br/...
13955,1477047577783123029,best place for ghost,78127165,Kaiying,Mitte,Alexanderplatz,52.522180,13.385800,Entire home/apt,8150.0,2,0,NaT,NaN,1,365,0,12/Z/AZ/123456-12
14009,1482600327601359961,Berlin Rooftop Loft mit Whirlpool & Aussicht,260167740,Alexander,Neukölln,Neuköllner Mitte/Zentrum,52.480710,13.425900,Entire home/apt,1088.0,1,0,NaT,NaN,9,61,0,Legal entity name and Legal form: Pearl 1 livi...

In [19]:
#remove prices that seem unrealistic such as 50k, 40k

df.loc[df['price'] > 5000, 'price'] = pd.NA

In [ ]:
#Creating columns

In [20]:
def price_category(price):
    if pd.isna(price):
        return 'Missing'
    elif price < 75:
        return 'Budget'
    elif price < 150:
        return 'Mid-range'
    elif price < 300:
        return 'Premium'
    else:
        return 'Luxury'

df['price_category'] = df['price'].apply(price_category)

In [21]:
def availability_category(days):
    if days == 0:
        return 'Unavailable'
    elif days <= 90:
        return 'Low availability'
    elif days <= 180:
        return 'Medium availability'
    else:
        return 'High availability'

df['availability_category'] = df['availability_365'].apply(availability_category)

In [22]:
df['has_license'] = df['license'].ne('No license info')

In [23]:
df['host_type'] = df['calculated_host_listings_count'].apply(
    lambda x: 'Single listing host' if x == 1 else 'Multi-listing host'
)

In [24]:
df['has_reviews'] = df['number_of_reviews'] > 0

In [25]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,...,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license,price_category,availability_category,has_license,host_type,has_reviews
0,3176,Fabulous Flat in great Location,3718,Britta,Pankow,Prenzlauer Berg Südwest,52.53471,13.41810,Entire home/apt,105.0,...,0.76,1,140,2,First name and Last name: Nicolas Krotz <br/> ...,Mid-range,Medium availability,True,Single listing host,True
1,9991,Geourgeous flat - outstanding views,33852,Philipp,Pankow,Prenzlauer Berg Südwest,52.53269,13.41805,Entire home/apt,135.0,...,0.06,1,241,0,03/Z/RA/003410-18,Mid-range,High availability,True,Single listing host,True
2,14325,Studio Apartment in Prenzlauer Berg,55531,Chris + Oliver,Pankow,Prenzlauer Berg Nordwest,52.54813,13.40366,Entire home/apt,75.0,...,0.14,4,168,0,NaN,Mid-range,Medium availability,True,Multi-listing host,True
3,17904,Beautiful Kreuzberg studio - 3 months minimum,68997,Matthias,Neukölln,Reuterstraße,52.49419,13.42166,Entire home/apt,32.0,...,1.57,1,72,1,NaN,Budget,Low availability,True,Single listing host,True
4,20858,Designer Loft in Berlin Mitte,71331,Marc,Pankow,Prenzlauer Berg Südwest,52.53711,13.40888,Entire home/apt,202.0,...,0.89,1,253,4,03/Z/RA/009767-24,Premium,High availability,True,Single listing host,True

In [26]:
df.to_csv('airbnb_berlin_cleaned.csv', index=False)

In [27]:
from sqlalchemy import create_engine

username = "postgres"
password = "postgr1"
host = "localhost"
port = "5432"
database = "airbnb"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name = "airbnb_berlin"
df.to_sql(table_name, engine, if_exists="replace", index=False)

274